title: dorianmarie.com
email: dorian@dorianmarie.com
description: >-
  dorian marié's website
baseurl: ""
url: https://dorianmarie.com
twitter_username: dorianmariecom
github_username: dorianmariecom
theme: minima
